import type { Metadata } from "next";
import * as React from "react";
import { Audiowide } from "next/font/google";
import "./globals.css";

const audioWide = Audiowide({
	weight: "400",
	subsets: ["latin"],
	variable: "--font-audiowide",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${audioWide.variable} antialiased `}>
				{children}
			</body>
		</html>
	);
}
